[package]
name = "flight_core"
version.workspace = true
edition.workspace = true

[dependencies]
nalgebra = "0.33"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
toml = "0.8"
rand = { version = "0.8", optional = true }
rand_distr = { version = "0.4", optional = true }

[features]
default = ["full-avionics"]
imu = ["rand", "rand_distr"]
gps = ["rand", "rand_distr"]
baro = ["rand", "rand_distr"]
magnetometer = ["rand", "rand_distr"]
airspeed = ["rand", "rand_distr"]
servo = []
esc = ["rand", "rand_distr"]
battery = []
flight_controller = []
avionics-sensors = ["imu", "gps", "baro", "magnetometer", "airspeed"]
avionics-power = ["esc", "battery"]
full-avionics = ["avionics-sensors", "avionics-power", "servo", "flight_controller"]
